### ISSUE TITLE
Exception while importing certain .mu files

### ISSUE THREAD

**Issue by blowfishpro** [taniwha/io_object_mu#12]
Attempt to load any of the `.mu` files in here: https://github.com/blowfishpro/B9-Aerospace/tree/master/GameData/B9_Aerospace_Legacy/Parts/Utility_Landing_Gear_HDG

Exception:

```
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_object_mu\import_mu.py", line 421, in execute
    return import_mu_op(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_object_mu\import_mu.py", line 398, in import_mu_op
    obj = process_mu(mu, os.path.dirname(filepath), create_colliders)
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_object_mu\import_mu.py", line 374, in process_mu
    return create_object(mu, mu.obj, None, create_colliders)
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_object_mu\import_mu.py", line 254, in create_object
    create_object(mu, child, obj, create_colliders)
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_object_mu\import_mu.py", line 257, in create_object
    create_action(mu, muobj.path, clip)
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\addons\io_object_mu\import_mu.py", line 172, in create_action
    if not obj.animation_data:
AttributeError: 'MuObject' object has no attribute 'animation_data'
```

**Comment by blowfishpro** [comment]
Per discussion on IRC, was introduced in 0e81cde
